name: Matriz de jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  os-and-version-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }} 
    steps: 
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.version }}
        - name: check node version
          run: node -v
