name: redis workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  redis_test:
    runs-on: ubuntu-latest
    container: unityofdisaster/ubuntu-with-redis-cli

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      
    steps: 
      - name: test redis connection
        run: redis-cli -h redis -p 6379 ping
      
      - name: insert value on redis cache
        run: redis-cli -h redis -p 6379 SET 97340108-0a71-41c2-a04c-8f05cd025559 "raymundo"

      - name: retrieve value on redis cache
        run: redis-cli -h redis -p 6379 GET 97340108-0a71-41c2-a04c-8f05cd025559
